import { parse, stringify, type INode } from 'svgson';

import { readNodeExportInfo } from '../utils/readNodeExportInfo';
import { writeNodeExportInfo } from '../utils/writeNodeExportInfo';
import { mapSvgsonNodes } from '../utils/mapSvgsonNodes';
import { normalizeFilterPrimitiveIds } from '../utils/normalizeFilterPrimitiveIds';

export async function applyNodeExportInfo(svg: string) {
  const svgNode = mapSvgsonNodes(await parse(svg), (node) => {
    let resultNode = node;

    const nodeExportInfo = readNodeExportInfo(node);

    writeNodeExportInfo(resultNode, null);

    // For the export, clip-path must be set in Figma so that the viewport has the correct height and width.
    // At this point we no longer need the ClipPath. It is automatically generated by the avatar when it is created.
    // SVGO will later automatically remove the corresponding element from "defs".
    delete resultNode.attributes['clip-path'];

    // Figma bakes static x/y/width/height into <mask> based on the design at export time.
    // At runtime DiceBear may apply per-component transforms (rotate/scale/translate) to
    // <use> inside masks, which can push the rendered shape past those bounds and clip it
    // (mask-type:alpha treats outside-bounds as fully transparent). Stripping the bounds
    // (and maskUnits) lets the SVG defaults take over: maskUnits=objectBoundingBox with
    // x=-10% y=-10% width=120% height=120%, sized to the masked element's bounding box.
    if (resultNode.name === 'mask') {
      delete resultNode.attributes['x'];
      delete resultNode.attributes['y'];
      delete resultNode.attributes['width'];
      delete resultNode.attributes['height'];
      delete resultNode.attributes['maskUnits'];
    }

    if (nodeExportInfo.componentGroup) {
      // The placeholder carries no attributes of its own, so the instance's
      // opacity would be lost with the node it replaces. It rides on a wrapper
      // group instead, which the definition converter folds onto the
      // reference.
      const opacity = resultNode.attributes?.opacity;

      resultNode = {
        name: '',
        type: 'text',
        value: `{{components.${nodeExportInfo.componentGroup}}}`,
        attributes: {},
        children: [],
      };

      if (typeof opacity === 'string') {
        resultNode = {
          name: 'g',
          type: 'element',
          value: '',
          attributes: { opacity },
          children: [resultNode],
        };
      }
    }

    // The definition paints these layers with `currentColor`, so the color
    // comes from whatever reference draws the component.
    if (nodeExportInfo.fillCurrentColor) {
      resultNode.attributes.fill = 'currentColor';
    }

    if (nodeExportInfo.strokeCurrentColor) {
      resultNode.attributes.stroke = 'currentColor';
    }

    if (nodeExportInfo.fillColorGroup) {
      resultNode.attributes.fill = `{{colors.${nodeExportInfo.fillColorGroup}}}`;

      // Figma bakes the bound style's paint opacity into fill-opacity. The
      // palette value carries that alpha channel itself, keeping the attribute
      // would apply it twice.
      delete resultNode.attributes['fill-opacity'];

      passPaintToChildren(resultNode, 'fill', nodeExportInfo.fillColorAlpha ?? 1);
    }

    if (nodeExportInfo.strokeColorGroup) {
      resultNode.attributes.stroke = `{{colors.${nodeExportInfo.strokeColorGroup}}}`;

      // See fill-opacity above.
      delete resultNode.attributes['stroke-opacity'];

      passPaintToChildren(resultNode, 'stroke', nodeExportInfo.strokeColorAlpha ?? 1);
    }

    if (nodeExportInfo.scale) {
      resultNode = {
        name: 'g',
        type: 'element',
        value: '',
        attributes: {
          transform: `scale(${nodeExportInfo.scale.x} ${nodeExportInfo.scale.y})`,
        },
        children: [resultNode],
      };
    }

    if (nodeExportInfo.matrix) {
      const matrix = nodeExportInfo.matrix;

      resultNode = {
        name: 'g',
        type: 'element',
        value: '',
        attributes: {
          transform: `matrix(${matrix.a} ${matrix.b} ${matrix.c} ${matrix.d} ${matrix.tx} ${matrix.ty})`,
        },
        children: [resultNode],
      };
    }

    // What the reference passes down to the `currentColor` layers of its
    // component. A placeholder is a text node and cannot carry attributes, so
    // it gets a wrapper group, which the definition converter folds back onto
    // the reference.
    if (nodeExportInfo.refColorGroup !== undefined || nodeExportInfo.refColorValue !== undefined) {
      if (resultNode.type !== 'element') {
        resultNode = {
          name: 'g',
          type: 'element',
          value: '',
          attributes: {},
          children: [resultNode],
        };
      }

      resultNode.attributes.color =
        nodeExportInfo.refColorGroup !== undefined
          ? `{{colors.${nodeExportInfo.refColorGroup}}}`
          : (nodeExportInfo.refColorValue as string);
    }

    if (nodeExportInfo.animations) {
      // Outside the transform wrappers: Figma composes motion outside the
      // node's resting transform, and the renderer wraps the whole element the
      // same way. URI-encoded so no svgo pass can touch the payload. The
      // animKey prefix keeps identically-animated siblings distinguishable for
      // `mergePaths`. An instance placeholder is a text node and cannot carry
      // attributes, so it gets a wrapper group when the transform was
      // identity.
      if (resultNode.type !== 'element') {
        resultNode = {
          name: 'g',
          type: 'element',
          value: '',
          attributes: {},
          children: [resultNode],
        };
      }

      resultNode.attributes['data-dbanim'] =
        `${nodeExportInfo.animKey ?? 0}:${encodeURIComponent(JSON.stringify(nodeExportInfo.animations))}`;

      // The resting state the animation replaces. Without it a layer that only
      // shows while animating would sit in the static avatar.
      if (nodeExportInfo.restingOpacity !== undefined) {
        resultNode.attributes.opacity = String(nodeExportInfo.restingOpacity);
      }
    }

    return resultNode;
  });

  normalizeFilterPrimitiveIds(svgNode);

  return stringify(svgNode);
}

/**
 * Hands the palette color down to the descendants of a bound node by dropping
 * their own paint. Their `*-opacity` is a value of their own, unlike the one on
 * the bound node, so it survives: in Figma it is absolute, while the inherited
 * color already carries the style's alpha, so the attribute becomes the share
 * the descendant adds on top of it. A descendant more opaque than the palette
 * value cannot be written that way and keeps the paint it came with.
 */
function passPaintToChildren(node: INode, channel: 'fill' | 'stroke', alpha: number): void {
  const opacityAttribute = `${channel}-opacity`;
  const groupKey = channel === 'fill' ? 'fillColorGroup' : 'strokeColorGroup';

  for (const child of node.children) {
    // A descendant bound to a palette of its own brings that palette's alpha
    // along and is rewritten when the walk reaches it.
    if (readNodeExportInfo(child)[groupKey]) {
      continue;
    }

    const own = child.attributes[opacityAttribute];
    const share = (own === undefined ? 1 : Number(own)) / alpha;

    if (false === Number.isFinite(share) || share > 1) {
      continue;
    }

    delete child.attributes[channel];

    if (share === 1) {
      delete child.attributes[opacityAttribute];
    } else {
      child.attributes[opacityAttribute] = String(share);
    }

    passPaintToChildren(child, channel, alpha);
  }
}
