import { DefinitionColors, DefinitionComponentBase, DefinitionComponents, Export, ExportColor } from '../types';
import { removeEmptyValuesFromObject } from '../utils/removeEmptyValuesFromObject';
import { toRangeObject, toScaleObject } from '../utils/rangeValue';
import { roundTo } from '../utils/roundTo';
import { createTemplateString } from './createTemplateString';
import { getLicenseAsText } from '../utils/getLicenseAsText';
import { parse } from 'svgson';
import { convertSvgsonToDefinition } from '../utils/convertSvgsonToDefinition';

const byCodepoint = (a: string, b: string): number => (a < b ? -1 : a > b ? 1 : 0);
const byEntryKey = ([a]: [string, unknown], [b]: [string, unknown]): number => byCodepoint(a, b);

const toSortedHexValues = (collection: Record<string, ExportColor>): string[] =>
  Object.entries(collection)
    .sort(byEntryKey)
    .map(([, v]) => `#${v.value}`);

export async function createExportDefinition(exportData: Export) {
  const precision = exportData.frame.settings.precision;
  const size = roundTo(((await figma.getNodeByIdAsync(exportData.frame.id)) as FrameNode).width, precision);
  const components: DefinitionComponents = {};
  const colors: DefinitionColors = {};

  // Collect components
  for (const [componentGroupKey, componentGroupValue] of Object.entries(exportData.components).sort(byEntryKey)) {
    if (componentGroupValue.extendsGroup) {
      components[componentGroupKey] = {
        extends: componentGroupValue.extendsGroup,
      };

      continue;
    }

    const rotation = componentGroupValue.settings.rotation;
    const scale = componentGroupValue.settings.scale;
    const probability = componentGroupValue.settings.probability;
    const translateX = componentGroupValue.settings.translateX;
    const translateY = componentGroupValue.settings.translateY;

    const baseEntry: DefinitionComponentBase = {
      width: 0,
      height: 0,
      rotate: toRangeObject(rotation),
      scale: toScaleObject(scale),
      probability: typeof probability === 'number' ? probability : undefined,
      translate: {
        x: toRangeObject(translateX),
        y: toRangeObject(translateY),
      },
      variants: {},
    };

    components[componentGroupKey] = baseEntry;

    for (const [componentKey, componentValue] of Object.entries(componentGroupValue.collection).sort(byEntryKey)) {
      const componentNode = (await figma.getNodeByIdAsync(componentValue.id)) as ComponentNode;
      const componentContent = await createTemplateString(exportData, componentNode);
      const componentContentWithSvg = `<svg>${componentContent}</svg>`;

      baseEntry.width = roundTo(Math.max(baseEntry.width, componentNode.width), precision);
      baseEntry.height = roundTo(Math.max(baseEntry.height, componentNode.height), precision);

      const weight = componentGroupValue.settings.weights[componentKey] ?? 1;

      baseEntry.variants[componentKey] = {
        elements: convertSvgsonToDefinition(await parse(componentContentWithSvg)).children ?? [],
        weight: weight === 1 ? undefined : weight,
      };
    }
  }

  // Collect background color
  if (exportData.frame.settings.backgroundColorGroupName) {
    const colorGroup = exportData.colors[exportData.frame.settings.backgroundColorGroupName];

    if (colorGroup) {
      colors['background'] = {
        values: toSortedHexValues(colorGroup.collection),
      };
    }
  }

  // Collect colors
  for (const [colorGroupKey, colorGroupValue] of Object.entries(exportData.colors).sort(byEntryKey)) {
    if (!colorGroupValue.isUsedByComponents) {
      continue;
    }

    const notEqualToCollection = colorGroupValue.settings.notEqualTo;
    const contrastTo = colorGroupValue.settings.contrastTo;

    colors[colorGroupKey] = {
      notEqualTo: Object.entries(notEqualToCollection)
        .filter(([key, value]) => {
          if (key === 'background' || exportData.colors[key]?.isUsedByComponents) {
            return value;
          }

          return false;
        })
        .map(([key]) => key)
        .sort(byCodepoint),
      contrastTo:
        contrastTo === 'background' || (contrastTo && exportData.colors[contrastTo]?.isUsedByComponents)
          ? contrastTo
          : undefined,
      values: toSortedHexValues(colorGroupValue.collection),
    };
  }

  // Create definition
  const bodyContent = await createTemplateString(exportData, (await figma.getNodeByIdAsync(exportData.frame.id)) as FrameNode);
  const bodyContentWithSvg = `<svg>${bodyContent}</svg>`;

  return JSON.stringify(
    removeEmptyValuesFromObject({
      $schema: 'https://cdn.hopjs.net/npm/@dicebear/schema@0.16.0/dist/definition.min.json',
      $comment:
        'This file was generated by the DiceBear Exporter for Figma. https://www.figma.com/community/plugin/1005765655729342787',
      meta: {
        license: {
          name: exportData.frame.settings.licenseName.trim(),
          url: exportData.frame.settings.licenseUrl.trim(),
          text: getLicenseAsText(exportData),
        },
        creator: {
          name: exportData.frame.settings.creator.trim(),
          url: exportData.frame.settings.homepage.trim(),
        },
        source: {
          name: exportData.frame.settings.sourceTitle.trim(),
          url: exportData.frame.settings.source.trim(),
        },
      },
      canvas: {
        elements: convertSvgsonToDefinition(await parse(bodyContentWithSvg)).children ?? [],
        width: size,
        height: size,
      },
      attributes: {
        fill: 'none',
        'shape-rendering': exportData.frame.settings.shapeRendering,
      },
      components: components,
      colors: colors,
    }),
    undefined,
    2
  );
}
